RUN_PARTS:
  SEGMENTATION: True
  INSTANCES: False
  MATCHING: False
SAVE_NAMES:
  SEGMENTATION: "segmentation.npy"
  INSTANCES: "instances.npy"
  MATCHING: "matching.npy"
LOAD_NAMES:
  SEGMENTATION: "segmentation.npy"
  INSTANCES: "instances.npy"
  MATCHING: "matching.npy"
DATA_PATH: ""
CUDA_CARD: 'cuda:0'
XML_FILE_NAME: "result.xml"
ANIMATION: False

MODEL_CONFIG_PATH: "" #path to cylinder model
MODEL_PARTITION_SIZE: 60
MODEL_VOXEL_SIZE: 0.15
MODEL_SAVE_DEBUG: False
MODEL_RETURN_UPSAMPLED: True
MODEL_SELECTION_STRATEGY: "last"
MODEL_MAX_NUM_PTS: 1000000
MAX_DISTANCE: 16
MIN_Z_HEIGHT: -20


POSTPROCESSING_INTENSITY_TRESH: 90