# Config format schema number
format_version: 4

###################
## Model options
model_params:
  model_architecture: "cylinder_asym"

  output_shape:
    - 200
    - 200
    - 25


  fea_dim: 7
  out_fea_dim: 32
  num_class: 2
  num_input_features: 4
  use_norm: True
  init_size: 32

###################
## Dataset options
dataset_params:
  dataset_type: "voxel_dataset"
  ignore_label: 30
  return_test: True
  fixed_volume_space: True
  max_volume_space:
    - 15
    - 15
    - 5
  min_volume_space:
    - -15
    - -15
    - -5

###################
## Data_loader options
train_dataset:
  use_bending: True
  bend_max_k: 0.05
  bend_max_len: 40
  use_intensity_jitter: False
  use_intensity_shift: True
  filenames_file: './train_filenames_large.pkl'
  use_gamma: False
  use_rsj: False


val_dataset:
  use_bending: True
  bend_max_k: 0.07
  bend_max_len: 40
  use_intensity_jitter: True
  use_intensity_shift: True
  filenames_file: './train_filenames_large.pkl'
  use_gamma: False
  use_rsj: False

test_dataset:
  use_bending: False
  bend_max_k: 0.07
  bend_max_len: 40
  use_intensity_jitter: False
  use_intensity_shift: False
  filenames_file: './train_filenames.pkl'
  use_gamma: False
  use_rsj: False

train_data_loader:
  return_ref: True
  batch_size: 1
  shuffle: True
  num_workers: 8


val_data_loader:
  return_ref: True
  batch_size: 1
  shuffle: True
  num_workers: 8
  
test_data_loader:
  return_ref: True
  batch_size: 1
  shuffle: False
  num_workers: 8


###################
## test params
train_params:
  model_load_path: "./test_55/best_val02000.pt"
  model_save_path: "./test_55/best_val02000.pt"
  checkpoint_every_n_steps: 100
  max_num_epochs: 50
  eval_every_n_steps: 1000
  learning_rate: 1e-2
  use_cut_mix: False
  checkpoint_save_path: './test_55/model_checkpoint02000.pt'
  weight_decay: 0

  save_vis: False
  vis_save_path: './test_55/'


